# Generated by Django 6.0.4 on 2026-05-01 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("genbank_interaction", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=50)),
                ("search_term", models.CharField(max_length=255)),
                ("total_records", models.IntegerField()),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
                ("search_accessions", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search History",
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accession", models.CharField(max_length=50)),
                ("title", models.TextField()),
                ("bp_length", models.IntegerField()),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                (
                    "ir_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_results",
                        to="genbank_interaction.ir_identification",
                        to_field="accession",
                    ),
                ),
            ],
        ),
    ]
